language: java
java:
    - "1.8"
before_install:
    - ./mvn_install_dependencies.sh
branches:
    only:
        - travis
        - master
install:
    - ./mvn_cmdline.sh
    - ./travis-config/setup_db.sh
    - ./mvn_serverplugins.sh
    - ./travis-config/setup_neo4j.sh
script:
    - true # we are just testing the build right now. need to define java unit tests to be run here
